### ISSUE TITLE
Fails to build with hdf5 1.12.0

### ISSUE THREAD

**Issue by opoplawski** [imageworks/Field3D#99]
Trying to build Field3D with hdf5 1.12.0 fails with:
```
/builddir/build/BUILD/Field3D-1.7.2/src/Field3DFileHDF5.cpp: In function 'herr_t Field3D::v1_7::InputFileHDF5::parsePartitions(hid_t, const char*, const H5L_info2_t*, void*)':
/builddir/build/BUILD/Field3D-1.7.2/src/Field3DFileHDF5.cpp:1138:71: error: too few arguments to function 'herr_t H5Oget_info_by_name3(hid_t, const char*, H5O_info2_t*, unsigned int, hid_t)'
 1138 |   status = H5Oget_info_by_name(loc_id, itemName, &infobuf, H5P_DEFAULT);
      |                                                                       ^
In file included from /usr/include/H5Apublic.h:22,
                 from /usr/include/hdf5.h:23,
                 from /builddir/build/BUILD/Field3D-1.7.2/src/Field3DFileHDF5.cpp:50:
/usr/include/H5Opublic.h:188:15: note: declared here
  188 | H5_DLL herr_t H5Oget_info_by_name3(hid_t loc_id, const char *name, H5O_info2_t *oinfo,
      |               ^~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/Field3D-1.7.2/src/Field3DFileHDF5.cpp: In function 'herr_t Field3D::v1_7::InputFileHDF5::parseLayers(hid_t, const char*, const H5L_info2_t*, void*)':
/builddir/build/BUILD/Field3D-1.7.2/src/Field3DFileHDF5.cpp:1178:72: error: too few arguments to function 'herr_t H5Oget_info_by_name3(hid_t, const char*, H5O_info2_t*, unsigned int, hid_t)'
 1178 |   status = H5Oget_info_by_name (loc_id, itemName, &infobuf, H5P_DEFAULT);
      |                                                                        ^
In file included from /usr/include/H5Apublic.h:22,
                 from /usr/include/hdf5.h:23,
                 from /builddir/build/BUILD/Field3D-1.7.2/src/Field3DFileHDF5.cpp:50:
/usr/include/H5Opublic.h:188:15: note: declared here
  188 | H5_DLL herr_t H5Oget_info_by_name3(hid_t loc_id, const char *name, H5O_info2_t *oinfo,
      |               ^~~~~~~~~~~~~~~~~~~~
```
See https://www.hdfgroup.org/2020/03/release-of-hdf5-1-12-0-newsletter-172 for some details

**Comment by hobbes1069** [comment]
Any progress on porting to the new API?

**Comment by v4hn** [comment]
For anyone else finding this:

Until upstream switches to the new API, you can use a compile definition to force HDF5 to the old API.

[Lunar Linux makes use of this for now](https://github.com/lunar-linux/moonbase-other/commit/704e52384002c434ad4c6847a866779cef73888a#diff-0f8bac1eaa8493c209adcad9ab3694fdR4).

**Comment by hobbes1069** [comment]
Checking in to see if there's been any movement towards adapting to the new API.
